import Vue from 'vue';
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faTwitter,
  faGithub,
  faCodepen,
  faOsi,
  faCss3Alt,
  faGit,
  faHtml5,
  faReact,
  faVuejs,
  faJs,
  faSass,
  faLess,
  faWordpress,
  faTypo3,
  faPhp,
  faAngular,
  faBootstrap,
  faLinux,
  faApple,
  faGulp,
  faGrunt,
  faYarn,
  faPython,
  faJenkins,
  faJira,
  faDocker,
  faNpm,
  faChrome,
  faFirefoxBrowser,
  faInternetExplorer,
  faUbuntu,
  faJava,
  faUnity,
  faAdobe,
  faSketch,
} from '@fortawesome/free-brands-svg-icons';
import {
  faExternalLinkAlt,
  faCodeBranch,
  faMobileAlt,
  faTabletAlt,
  faDesktop,
  faBezierCurve,
  faPalette,
  faDraftingCompass,
  faMagic,
} from '@fortawesome/free-solid-svg-icons';
import {
  faMoon,
  faHandPointer,
} from '@fortawesome/free-regular-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import App from './App.vue';

library.add(
  faTwitter,
  faGithub,
  faCodepen,
  faOsi,
  faCss3Alt,
  faGit,
  faHtml5,
  faReact,
  faVuejs,
  faJs,
  faSass,
  faLess,
  faWordpress,
  faTypo3,
  faPhp,
  faAngular,
  faBootstrap,
  faLinux,
  faApple,
  faGulp,
  faGrunt,
  faYarn,
  faPython,
  faJenkins,
  faJira,
  faDocker,
  faNpm,
  faChrome,
  faFirefoxBrowser,
  faInternetExplorer,
  faUbuntu,
  faJava,
  faUnity,
  faNpm,
  faGithub,
  faCodeBranch,
  faExternalLinkAlt,
  faMobileAlt,
  faTabletAlt,
  faDesktop,
  faAdobe,
  faSketch,
  faBezierCurve,
  faPalette,
  faDraftingCompass,
  faMoon,
  faHandPointer,
  faMagic,
);
Vue.component('font-awesome-icon', FontAwesomeIcon);
Vue.config.productionTip = false;

new Vue({
  render: (h) => h(App),
}).$mount('#app');
